const CATEGORY_DATA=[
 {id:'all',name:'All guides',icon:'⌕',count:'Browse',url:'https://www.tilingsuppliesdirect.co.uk/shop'},
 {id:'backer',name:'Backer boards',icon:'▦',count:'41 products',url:'https://www.tilingsuppliesdirect.co.uk/product-category/wetroom-systems/tile-backer-board'},
 {id:'waterproofing',name:'Waterproofing',icon:'◒',count:'97+ products',url:'https://www.tilingsuppliesdirect.co.uk/product-category/wetroom-systems/waterproofing-tanking-products'},
 {id:'adhesive',name:'Adhesives',icon:'◆',count:'72 products',url:'https://www.tilingsuppliesdirect.co.uk/product-category/tile-adhesive-grout-levelling-compounds/tile-adhesives'},
 {id:'grout',name:'Grout & sealants',icon:'≋',count:'35+ grouts',url:'https://www.tilingsuppliesdirect.co.uk/product-category/tile-adhesive-grout-levelling-compounds/tile-grout'},
 {id:'levelling',name:'Levelling & primers',icon:'↔',count:'102 products',url:'https://www.tilingsuppliesdirect.co.uk/product-category/tile-adhesive-grout-levelling-compounds'},
 {id:'decoupling',name:'Decoupling',icon:'▤',count:'41 products',url:'https://www.tilingsuppliesdirect.co.uk/product-category/wetroom-systems/decoupling-membranes'},
 {id:'ufh',name:'Underfloor heating',icon:'♨',count:'54 products',url:'https://www.tilingsuppliesdirect.co.uk/product-category/wetroom-systems/underfloor-heating'},
 {id:'trim',name:'Trims & profiles',icon:'⌞',count:'420 products',url:'https://www.tilingsuppliesdirect.co.uk/product-category/tile-trim'},
 {id:'outdoor',name:'Outdoor systems',icon:'△',count:'128 products',url:'https://www.tilingsuppliesdirect.co.uk/product-category/outdoor-tiling'},
 {id:'treatment',name:'Cleaning & protection',icon:'✦',count:'172 products',url:'https://www.tilingsuppliesdirect.co.uk/product-category/surface-treatments'},
 {id:'tools',name:'Tools & consumables',icon:'◇',count:'565 products',url:'https://www.tilingsuppliesdirect.co.uk/product-category/tools-consumables'},
 {id:'flooring',name:'LVT & flooring',icon:'▰',count:'89 products',url:'https://www.tilingsuppliesdirect.co.uk/product-category/lvt-and-flooring-supplies'}
];

const PRODUCTS=[
 {id:'jackoboard-plano',name:'JACKOBOARD Plano Tile Backer Board',brand:'JACKOBOARD',category:'backer',summary:'Lightweight XPS construction board with a coated tile-ready surface for wall, floor and bathroom construction applications.',flags:{Walls:true,Floors:true,'Wet areas':true,External:false},uses:['Creating a stable tile-ready background on walls and suitable floors','Bathroom and shower construction','Boxing, niches, shelves, bath panels and other formed details','Adding thermal insulation beneath a tiled finish'],consider:['The board itself is water-repellent, but wet-area joints, penetrations and fixings still need to be sealed as a complete system.','The fixing method and minimum board thickness depend on the substrate and application.','Floor installation has specific substrate, adhesive, reinforcement and tile-size requirements—check the floor instructions before specifying.'],pairings:[['JACKOBOARD Board Fix Adhesive','Bonds/seals board joints and can be used as part of the specified sealing detail.'],['JACKOBOARD Galvanised Fixing Washers','Spreads mechanical fixing load when boards are screwed to suitable timber/stud substrates.'],['JACKOBOARD Glass Fibre Tape','Reinforces board joints before tiling and is used in specified joint treatments.'],['JACKOBOARD Sealing Tape / sealing components','Used where the system requires waterproof sealing at joints, corners and penetrations.'],['Suitable C2 / flexible tile adhesive','Required for bedding or tiling depending on the application and manufacturer instructions.']],docs:[['Technical specifications','https://www.jackon-insulation.com/downloads-service/download/jackoboard-technical-specifications'],['Wall installation PDF','https://www.jackon-insulation.com/downloads-service/download/jackoboard-plano-wall'],['Floor installation PDF','https://www.jackon-insulation.com/downloads-service/download/jackoboard-plano-floor'],['BBA construction board certificate','https://www.jackon-insulation.com/downloads-service/download/jackoboard-bba-construction-boards'],['Manufacturer product page','https://www.jackon-insulation.com/products/detail/jackoboard-plano']],buy:'https://www.tilingsuppliesdirect.co.uk/product-category/wetroom-systems/tile-backer-board',source:'Manufacturer + Tiling Supplies Direct'},
 {id:'wedi-board',name:'wedi Tile Backer Board',brand:'wedi',category:'backer',summary:'XPS-core tile backer board reinforced and cement-coated on both sides, designed as a lightweight waterproof tile substrate.',flags:{Walls:true,Floors:true,'Wet areas':true,External:'Check'},uses:['Tile substrate in bathrooms and wet rooms','Wall and suitable residential floor build-ups','Creating insulated tiled surfaces and construction details'],consider:['Use the correct wedi fixing and joint-sealing system for the background.','Special applications such as external areas, pools or unusual temperatures should be checked with wedi.','Floor use is subject to load and system limitations.'],pairings:[['wedi fixing washers / dowels','For mechanically fixing boards where the substrate and installation method require it.'],['wedi 610 adhesive sealant','For system-compatible bonding and sealing details.'],['wedi board connectors','Useful where a construction detail requires board-to-board connection.']],docs:[['Supplier product & technical links','https://www.tilingsuppliesdirect.co.uk/product/wedi-tile-backer-board']],buy:'https://www.tilingsuppliesdirect.co.uk/product/wedi-tile-backer-board',source:'Tiling Supplies Direct'},
 {id:'hardiebacker',name:'HardieBacker Board 6mm & 12mm',brand:'James Hardie',category:'backer',summary:'Cement-based tile backer board for robust, dimensionally stable tiled backgrounds on suitable walls and floors.',flags:{Walls:true,Floors:true,'Wet areas':true,External:'Check'},uses:['6mm over suitable timber floors or existing suitable wall backgrounds','12mm on suitable stud walls','Heavy tiled wall finishes where the full system is correctly designed'],consider:['Board thickness and fixing pattern vary by application.','Joints need the specified alkali-resistant tape and adhesive treatment.','Wet areas still require the project waterproofing specification to be followed.'],pairings:[['HardieBacker fixing screws','Specified mechanical fixings for suitable timber/stud installations.'],['HardieTape / alkali-resistant tape','Reinforces board joints before tiling.'],['HardieBacker scoring knife','Designed to score and snap the board cleanly.']],docs:[['Supplier product & manufacturer links','https://www.tilingsuppliesdirect.co.uk/product/hardiebacker-board-6mm-12mm']],buy:'https://www.tilingsuppliesdirect.co.uk/product/hardiebacker-board-6mm-12mm',source:'Tiling Supplies Direct'},
 {id:'dukkaboard-panel',name:'Tile Backer Board Panels',brand:'Dukkaboard / TSD',category:'backer',summary:'Lightweight XPS-core, cement-coated tile backer panels for suitable walls and floors, including insulating build-ups.',flags:{Walls:true,Floors:true,'Wet areas':true,External:'Check'},uses:['Replacing unsuitable sheet backgrounds with a tile-ready substrate','Overboarding suitable walls and floors','Adding insulation beneath underfloor heating'],consider:['Select thickness and fixing method for the substrate.','Treat wet-area joints and penetrations as part of a waterproof system.'],pairings:[['Tile Backer Board fixing washers','Helps mechanically secure panels to suitable substrates.']],docs:[['Supplier product page','https://www.tilingsuppliesdirect.co.uk/product/tile-backer-board-panels']],buy:'https://www.tilingsuppliesdirect.co.uk/product/tile-backer-board-panels',source:'Tiling Supplies Direct'},
 {id:'board-fix',name:'JACKOBOARD Board Fix Adhesive 290ml',brand:'JACKOBOARD',category:'waterproofing',summary:'Single-component SMP mounting adhesive and sealant used with JACKOBOARD and other compatible construction-board details.',flags:{Walls:true,Floors:true,'Wet areas':true,External:'Check'},uses:['Bonding JACKOBOARD elements together','Sealing specified board joints and fixing penetrations','Bonding board products to suitable substrates'],consider:['Use as part of the manufacturer system, not as a substitute for an unverified waterproofing design.','Not suitable for bonding raw aluminium without the required pretreatment.'],pairings:[['JACKOBOARD Plano','Primary construction board system product.'],['Glass fibre tape / sealing components','Required in certain specified joint and sealing details.']],docs:[['Supplier product page','https://www.tilingsuppliesdirect.co.uk/product/jackoboard-board-fix-adhesive-290ml'],['JACKOBOARD manufacturer system page','https://www.jackon-insulation.com/products/detail/jackoboard-plano']],buy:'https://www.tilingsuppliesdirect.co.uk/product/jackoboard-board-fix-adhesive-290ml',source:'Tiling Supplies Direct + manufacturer'},
 {id:'jackoboard-washers',name:'JACKOBOARD Galvanised Fixing Washers',brand:'JACKOBOARD',category:'waterproofing',summary:'35mm galvanised fixing washers used to mechanically fix suitable tile backer and insulation boards.',flags:{Walls:true,Floors:'System', 'Wet areas':true,External:'Check'},uses:['Fixing JACKOBOARD Plano to suitable timber stud backgrounds','Spreading screw load across soft construction-board surfaces'],consider:['In wet areas the screw/washer penetration must be sealed using the specified waterproof detail.','Use the correct fixing quantity and screw type for the board size and substrate.'],pairings:[['JACKOBOARD Board Fix','Can seal the washer/fixing penetration in specified system details.'],['JACKOBOARD sealing tape / membrane','Alternative specified method for sealing penetrations.']],docs:[['Supplier product page','https://www.tilingsuppliesdirect.co.uk/product/jackoboard-galvanised-fixing-washers']],buy:'https://www.tilingsuppliesdirect.co.uk/product/jackoboard-galvanised-fixing-washers',source:'Tiling Supplies Direct'},
 {id:'bal-rapid-flex-one',name:'BAL Rapid Flex One Tile Adhesive 20kg',brand:'BAL',category:'adhesive',summary:'Rapid-setting, highly polymer-modified cementitious wall and floor tile adhesive for a broad range of internal and external applications.',flags:{Walls:true,Floors:true,'Wet areas':true,External:true},uses:['Ceramic and porcelain tile fixing','Many natural-stone, mosaic and terrazzo installations','Dry and wet internal environments','Suitable specified external tile installations'],consider:['Check stone sensitivity and substrate compatibility before choosing a white cementitious adhesive.','Rapid setting shortens working time—plan mixing quantities accordingly.','Background preparation, movement provision and coverage still control installation success.'],pairings:[['Suitable primer','Needed on substrates where BAL specifies priming.'],['Compatible grout','Choose grout for joint width, exposure and movement conditions.'],['Waterproofing system','Wet areas may require tanking before fixing.']],docs:[['Supplier product & datasheet link','https://www.tilingsuppliesdirect.co.uk/product/bal-rapid-flex-one-tile-adhesive']],buy:'https://www.tilingsuppliesdirect.co.uk/product/bal-rapid-flex-one-tile-adhesive',source:'Tiling Supplies Direct'},
 {id:'bal-flex-one',name:'BAL Flex One Tile Adhesive 20kg',brand:'BAL',category:'adhesive',summary:'Standard-setting S1-class flexible white tile adhesive for suitable walls, floors, wet areas and external installations.',flags:{Walls:true,Floors:true,'Wet areas':true,External:true},uses:['Where a longer working time than a rapid-set adhesive is useful','Porcelain, ceramic, mosaics and many natural stones','Suitable prepared heated and movement-prone backgrounds'],consider:['Some backgrounds require primers, additives or decoupling systems—follow the substrate-specific instructions.','In wet areas, waterproofing requirements are separate from adhesive selection.'],pairings:[['BAL Prime APD / specified primer','Required on selected absorbent or calcium-sulphate backgrounds.'],['BAL Rapid Mat / compatible decoupling','May be specified on selected timber or movement-prone backgrounds.']],docs:[['Supplier product & datasheet link','https://www.tilingsuppliesdirect.co.uk/product/bal-flex-one-tile-adhesive']],buy:'https://www.tilingsuppliesdirect.co.uk/product/bal-flex-one-tile-adhesive',source:'Tiling Supplies Direct'},
 {id:'mapesil-ac',name:'Mapei Mapesil AC Silicone Sealant',brand:'Mapei',category:'grout',summary:'Acetic-crosslinking mould-resistant silicone sealant available in a broad range of colours coordinated with Mapei grout ranges.',flags:{Walls:true,Floors:true,'Wet areas':true,External:true},uses:['Elastic seals at suitable tile junctions and movement locations','Colour-matched finishing alongside Mapei grouts','Suitable ceramic, glass and anodised-aluminium sealing details'],consider:['Acetic silicone is not appropriate for every natural stone or substrate—check compatibility.','Sealant joints need the correct geometry and, where required, backing material.','A movement joint should not be rigidly filled with grout.'],pairings:[['Mapei Ultracolor Plus grout','Colour-coordinated grout option for field joints.'],['Mapefoam backing rod','Controls joint depth and helps avoid three-sided adhesion.'],['UltraCare Smooth finishing spray','Aids tooling of the uncured silicone surface.']],docs:[['Supplier product & datasheet link','https://www.tilingsuppliesdirect.co.uk/product/mapei-mapesil-ac-silicone-sealant']],buy:'https://www.tilingsuppliesdirect.co.uk/product/mapei-mapesil-ac-silicone-sealant',source:'Tiling Supplies Direct'},
 {id:'prolevel-fibre',name:'Ultra Tile Fix ProLevel Fibre 20kg',brand:'UltraTile',category:'levelling',summary:'Fibre-reinforced, rapid-drying floor levelling compound designed to create a strong, even base before tiling.',flags:{Walls:false,Floors:true,'Wet areas':'Check',External:'Check'},uses:['Levelling suitable uneven floor substrates','Creating a tile-ready base in appropriate floor build-ups','Applications requiring a fibre-reinforced leveller'],consider:['Substrate preparation and primer choice matter as much as the leveller itself.','Confirm permitted depth, moisture condition and covering time for the specific project.'],pairings:[['Specified primer','Controls suction and supports bond to the intended substrate.'],['Spiked roller / levelling tools','Useful where required by the chosen application method.']],docs:[['Supplier product page','https://www.tilingsuppliesdirect.co.uk/product/ultra-tile-fix-prolevel-fibre-levelling-compound']],buy:'https://www.tilingsuppliesdirect.co.uk/product/ultra-tile-fix-prolevel-fibre-levelling-compound',source:'Tiling Supplies Direct'},
 {id:'ditra',name:'Schluter DITRA Matting Decoupling Membrane',brand:'Schluter',category:'decoupling',summary:'Decoupling membrane used between suitable substrates and tiled finishes to manage differential movement and protect the tile layer.',flags:{Walls:false,Floors:true,'Wet areas':'System',External:'Check'},uses:['Movement-prone floor build-ups','New screeds and selected problematic substrates','Tiled floors where uncoupling is required'],consider:['Decoupling is not a substitute for fixing an unstable substrate.','Waterproof performance depends on the complete sealed system and correct detailing.'],pairings:[['Compatible tile adhesive','Used below/above the membrane as specified for the background and tile.'],['Schluter sealing tape/components','Needed where the membrane is being detailed as a waterproof system.']],docs:[['Supplier category & product access','https://www.tilingsuppliesdirect.co.uk/product-category/wetroom-systems/decoupling-membranes']],buy:'https://www.tilingsuppliesdirect.co.uk/product-category/wetroom-systems/decoupling-membranes',source:'Tiling Supplies Direct'},
 {id:'mapeguard-um35',name:'Mapei Mapeguard UM35 Decoupling Membrane',brand:'Mapei',category:'decoupling',summary:'Decoupling membrane option for tiled floors where movement management and system detailing are required.',flags:{Walls:false,Floors:true,'Wet areas':'System',External:'Check'},uses:['Suitable movement-prone tiled floor systems','Selected heated floor build-ups','Projects requiring a decoupling layer beneath tile'],consider:['Use the manufacturer installation system and adhesive recommendations.','Check whether waterproofing is required separately or as part of the membrane system.'],pairings:[['Compatible Mapei adhesive','Select to suit substrate, membrane and tile type.'],['System sealing accessories','Required where waterproof detailing is specified.']],docs:[['Supplier category','https://www.tilingsuppliesdirect.co.uk/product-category/wetroom-systems/decoupling-membranes']],buy:'https://www.tilingsuppliesdirect.co.uk/product-category/wetroom-systems/decoupling-membranes',source:'Tiling Supplies Direct'},
 {id:'ditra-heat',name:'Schluter DITRA HEAT Matting',brand:'Schluter',category:'ufh',summary:'Uncoupling mat designed to accept the matching electric heating cable as part of a tiled underfloor-heating system.',flags:{Walls:false,Floors:true,'Wet areas':'System',External:false},uses:['Electric underfloor heating beneath suitable tile and stone','Combining cable positioning with uncoupling in one floor layer'],consider:['Electrical work, testing and thermostat installation must follow the applicable instructions and regulations.','Plan sensor position, heated area and cable spacing before installation.'],pairings:[['DITRA HEAT E heating cable','The matching heating cable for the membrane system.'],['Compatible thermostat and sensor','Controls the floor heating system.'],['Cable tester','Allows resistance/continuity checks during installation.']],docs:[['Supplier underfloor heating range','https://www.tilingsuppliesdirect.co.uk/product-category/wetroom-systems/underfloor-heating']],buy:'https://www.tilingsuppliesdirect.co.uk/product-category/brands/schluter/schluter-underfloor-heating-systems',source:'Tiling Supplies Direct'},
 {id:'pp-level-duo',name:'Mapei PP Level Duo Maxi Paving Pedestal System',brand:'Mapei / Profilpas',category:'outdoor',summary:'Adjustable self-levelling pedestal system for raised external floors using porcelain pavers, stone or suitable decking.',flags:{Walls:false,Floors:true,'Wet areas':false,External:true},uses:['Raised porcelain paving','Terraces, balconies, rooftops and pool-edge areas','Creating drainage/service voids beneath an elevated finish'],consider:['Pedestal spacing and slab suitability must be designed for the paver size, load and project.','Perimeters, steps and vertical closures need specific detailing.','Choose the correct head joint width, base height and extensions before ordering.'],pairings:[['2mm / 3mm / 4mm levelling heads','Selects the intended joint width between supported pavers.'],['Height extensions','Increase pedestal build-up where the base range is insufficient.'],['Adjustment key','Allows height adjustment on compatible 4mm-joint configurations.']],docs:[['Supplier product & datasheet link','https://www.tilingsuppliesdirect.co.uk/product/mapei-pp-level-duo-maxi-paving-pedestal-system']],buy:'https://www.tilingsuppliesdirect.co.uk/product/mapei-pp-level-duo-maxi-paving-pedestal-system',source:'Tiling Supplies Direct'},
 {id:'ditra-drain',name:'Schluter DITRA DRAIN 4 & 8',brand:'Schluter',category:'outdoor',summary:'Drainage and uncoupling membrane for suitable tiled or paved external build-ups.',flags:{Walls:false,Floors:true,'Wet areas':false,External:true},uses:['External tiled terraces and balconies where drainage/uncoupling is specified','Managing moisture movement beneath compatible finishes'],consider:['Falls, drainage outlets, waterproofing and edge details need to be designed as a complete external system.'],pairings:[['Compatible waterproofing layer','External drainage matting does not replace the required substrate waterproofing design.'],['Suitable external adhesive/mortar','Must match the tile, substrate and exposure.']],docs:[['Supplier decoupling category','https://www.tilingsuppliesdirect.co.uk/product-category/landscaping-products/outdoor-decoupling-membranes']],buy:'https://www.tilingsuppliesdirect.co.uk/product-category/landscaping-products/outdoor-decoupling-membranes',source:'Tiling Supplies Direct'},
 {id:'mapesil-tools',name:'Mapei UltraCare Smooth Silicone Finishing Spray',brand:'Mapei',category:'tools',summary:'Finishing aid used while tooling compatible silicone sealant joints.',flags:{Walls:true,Floors:true,'Wet areas':true,External:'Check'},uses:['Helping form a compact, neat silicone finish before skinning'],consider:['Use only as directed with compatible sealants; it does not replace correct joint preparation.'],pairings:[['Mapei Mapesil AC','Commonly used alongside Mapesil when tooling the sealant.'],['Sealant gun','Required to extrude cartridge-applied sealants.']],docs:[['Supplier silicone & accessory category','https://www.tilingsuppliesdirect.co.uk/product-category/tools-consumables/silicones-adhesives-resins-tools-accessories']],buy:'https://www.tilingsuppliesdirect.co.uk/product-category/tools-consumables/silicones-adhesives-resins-tools-accessories',source:'Tiling Supplies Direct'},
 {id:'hardie-knife',name:'HardieBacker Score & Snap Knife',brand:'James Hardie',category:'tools',summary:'Hand tool intended for scoring cement backer board so suitable sheets can be snapped to size.',flags:{Walls:true,Floors:true,'Wet areas':false,External:false},uses:['Scoring HardieBacker and suitable board products during setting-out'],consider:['Use appropriate PPE and follow the board manufacturer cutting instructions.'],pairings:[['HardieBacker Board','The board this tool is intended to cut.']],docs:[['Supplier tools category','https://www.tilingsuppliesdirect.co.uk/product-category/tools-consumables/hand-tools-consumables']],buy:'https://www.tilingsuppliesdirect.co.uk/product-category/tools-consumables/hand-tools-consumables',source:'Tiling Supplies Direct'}
];

let selectedCategory='all';
const categoryGrid=document.querySelector('#category-grid');
const productGrid=document.querySelector('#product-grid');
const listTitle=document.querySelector('#product-list-title');
const listMeta=document.querySelector('#product-list-meta');
const supplierLink=document.querySelector('#supplier-category-link');
const searchInput=document.querySelector('#product-search');
const searchButton=document.querySelector('#product-search-button');
const dialog=document.querySelector('#product-dialog');
const detail=document.querySelector('#product-detail');

function renderCategories(){categoryGrid.innerHTML=CATEGORY_DATA.map(c=>`<button class="category-card ${c.id===selectedCategory?'active':''}" data-category="${c.id}"><span class="category-icon">${c.icon}</span><span><strong>${c.name}</strong><small>${c.count}</small></span></button>`).join('');categoryGrid.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{selectedCategory=b.dataset.category;renderCategories();renderProducts();document.querySelector('#products-list').scrollIntoView({behavior:'smooth',block:'start'})}))}
function flagClass(v){return v===true?'yes':''}
function flagLabel(k,v){if(v===true)return `${k} ✓`;if(v===false)return `${k} —`;return `${k}: ${v}`}
function filteredProducts(){const q=searchInput.value.trim().toLowerCase();return PRODUCTS.filter(p=>(selectedCategory==='all'||p.category===selectedCategory)&&(!q||[p.name,p.brand,p.summary,p.category,...p.uses].join(' ').toLowerCase().includes(q)))}
function renderProducts(){const cat=CATEGORY_DATA.find(c=>c.id===selectedCategory)||CATEGORY_DATA[0];const items=filteredProducts();listTitle.textContent=selectedCategory==='all'?'Product guides':cat.name;listMeta.textContent=`${items.length} enriched guide${items.length===1?'':'s'} shown. Full supplier range available from the category link.`;supplierLink.href=cat.url;supplierLink.textContent=selectedCategory==='all'?'Open full supplier catalogue ↗':`Browse all ${cat.name.toLowerCase()} ↗`;if(!items.length){const q=encodeURIComponent(searchInput.value.trim());productGrid.innerHTML=`<div class="empty-state"><h3>No enriched guide matches that search yet.</h3><p>The supplier catalogue is larger than the verified TC100 guide database. Search the live supplier range, then use manufacturer literature before specifying.</p><a target="_blank" rel="noopener" href="https://www.tilingsuppliesdirect.co.uk/?s=${q}&post_type=product">Search Tiling Supplies Direct for this product ↗</a></div>`;return}productGrid.innerHTML=items.map(p=>`<article class="product-card"><div class="product-card-top"><span class="brand-chip">${p.brand}</span><h3>${p.name}</h3><p>${p.summary}</p><div class="use-flags">${Object.entries(p.flags).map(([k,v])=>`<span class="use-flag ${flagClass(v)}">${flagLabel(k,v)}</span>`).join('')}</div></div><div class="product-card-actions"><button class="guide-button" data-guide="${p.id}">Open guide</button><a class="buy-button" target="_blank" rel="noopener" href="${p.buy}">View supplier ↗</a></div></article>`).join('');productGrid.querySelectorAll('[data-guide]').forEach(b=>b.addEventListener('click',()=>openGuide(b.dataset.guide)))}
function openGuide(id){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;detail.innerHTML=`<div class="product-detail-head"><span class="brand-chip">${p.brand}</span><h2>${p.name}</h2><p>${p.summary}</p></div><div class="detail-flags">${Object.entries(p.flags).map(([k,v])=>`<div class="detail-flag"><strong>${v===true?'✓':v===false?'—':v}</strong>${k}</div>`).join('')}</div><div class="detail-grid"><section class="detail-box"><h3>What is it used for?</h3><ul>${p.uses.map(x=>`<li>${x}</li>`).join('')}</ul></section><section class="detail-box"><h3>Consider before buying</h3><ul>${p.consider.map(x=>`<li>${x}</li>`).join('')}</ul></section><section class="detail-box full"><h3>If you buy this, what else may you need?</h3><div class="pairing-list">${p.pairings.map(([a,b])=>`<div class="pairing-item"><strong>${a}</strong><span>${b}</span></div>`).join('')}</div></section><section class="detail-box full"><h3>Datasheets & technical information</h3><div class="doc-links">${p.docs.map(([a,b])=>`<a href="${b}" target="_blank" rel="noopener">${a} ↗</a>`).join('')}</div><p>Source: ${p.source}. Always check the current manufacturer document before installation; product instructions can change.</p></section></div><div class="detail-actions"><a class="primary" href="${p.buy}" target="_blank" rel="noopener">View / buy from supplier ↗</a><a class="secondary" href="https://www.tilingsuppliesdirect.co.uk/shop" target="_blank" rel="noopener">Open full catalogue ↗</a></div>`;dialog.showModal()}
function doSearch(){renderProducts();document.querySelector('#products-list').scrollIntoView({behavior:'smooth',block:'start'})}
searchButton.addEventListener('click',doSearch);searchInput.addEventListener('keydown',e=>{if(e.key==='Enter')doSearch()});searchInput.addEventListener('input',()=>{if(!searchInput.value)renderProducts()});document.querySelector('#product-dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
renderCategories();renderProducts();
